name: Shellcheck Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: List shell files
        run: |
          echo "Searching for shell files:"
          find . -type f -name "*.sh"

      - name: Run ShellCheck
        run: |
          for file in $(find . -type f -name "*.sh"); do
            echo "Running shellcheck on $file"
            shellcheck "$file"
          done
